name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test (Node ${{ matrix.node }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [8, 10, 12, 13]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Use Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install NPM dependencies
      run: npm ci

    - name: Run unit tests
      run: npm test
      env:
        CI: true

    - name: Run integration tests
      run: npm run integrate
      env:
        CI: true
